In [ ]:
# Introducing Numpy Arrays
# Numpy is a numerical computing module in Python.
# In order to use Numpy module, we need to import it first.
# A conventional way to import it is to use "np" as a shortened name.
# Of course, you could call it any name,
# but conventionally, "np" is accepted
# by the whole community and it is a good practice to use it.


In [ ]:
import numpy as np

In [ ]:
# To define an array in Python, you could use
# the np.array function to convert a list.

In [ ]:
# E.g1: Create the following arrays:
# x = (1 4 3)
# y = (1 4 3
#      9 2 7)
x = np.array([1,4,3])
print(x)
y = np.array([[1,4,3],[9,2,7]])
print(y)

[1 4 3]
[[1 4 3]
 [9 2 7]]


In [ ]:
# NOTE! A 2-D array could use a nested lists to represent,
# with the inner list representing each row.

In [ ]:
# Many times we would like to know the size or length of an array.
# The array shape attribute is called on an array y and returns
# a 2 × 3 array where the first element is the number of
# rows in the matrix y
# and the second element is the number of columns in y.
# Note that the output of the shape attribute is a tuple.
# The size attribute is called on an array y and returns
# the total number of elements in matrix y.

In [ ]:
# Ex:  Find the rows, columns and the total size for array y.
# Number of rows:
print(y.shape[0])
# Number of columns:
print(y.shape[1])
# Total number of elements in y:
print(y.size)

2
3
6


In [ ]:
# Difference between attribute and method
# Attributes are characteristics of an object, while methods
# are functions that act on an object

In [ ]:
# Note:
# Remember that when we call a method on an object,
# we need to use the parentheses, while the attributes don’t.

In [ ]:
# Very often we would like to generate arrays
# that have a structure or pattern.
# For instance, we may wish to create the array
# z = [1 2 3 ... 2000].
# It would be very cumbersome to type the
# entire description of z into Python.
# For generating arrays that are in order and evenly spaced,
# it is useful to use the arange function in Numpy.

In [ ]:
# E.g: Create an array z from 1 to 2000 with an increment 1.
z = np.arange(1,2001,1)
print(z)

[   1    2    3 ... 1998 1999 2000]


In [ ]:
# Using the np.arange, we could create z easily.
# The first two numbers are the start and end of the sequence,
# and the last one is the increment.
# Since it is very common to have an increment of 1,
# if an increment is not specified,
# Python will use a default value of 1.
# Therefore np.arange(1, 2000) will have the same result
# as np.arange(1, 2000, 1).
# Negative or noninteger increments can also be used.
# If the increment “misses” the last value,
# it will only extend until the value just before the ending value.
# For example, x = np.arange(1,8,2) would be [1, 3, 5, 7].

In [ ]:
# Ex: Generate an array with [0.5, 1, 1.5, 2, 2.5].
h = np.arange(0.5,3,.5)
print(h)

In [ ]:
# Sometimes we want to guarantee a start and
# end point for an array but still have evenly spaced elements.
# For instance, we may want an array
# that starts at 1, ends at 8, and has exactly 10 elements.
# For this purpose you can use the function np.linspace.
# linspace takes three input values separated by commas.
# So A = linspace(a,b,n) generates an array of n equally spaced
# elements starting from a and ending at b.

In [ ]:
# Ex: Use linspace to generate an array starting at 3,
# ending at 9, and containing 10 elements.
A = np.linspace(3,9,10)
print(A)

[3.         3.66666667 4.33333333 5.         5.66666667 6.33333333
 7.         7.66666667 8.33333333 9.        ]


In [ ]:
# Getting access to the 1D numpy array is
# similar to what we described for lists or tuples,
# it has an index to indicate the location.
# For example:
x = np.array([1,4,3])
print(x)
# get the 2nd element of x
print(x[1])

[1 4 3]
4


In [ ]:
# get all the element from the 2nd element of x
print(x[1:])

[4 3]


In [ ]:
# get the last element of x
print(x[-1])

3


In [ ]:
# For 2D arrays, it is slightly different,
# since we have rows and columns.
# To get access to the data in a 2D array M,
# we need to use M[r, c], that the row r and column c
# are separated by comma.
# This is referred to as array indexing.
# The r and c could be single number, a list and so on.
# If you only think about the row index or the column index,
# then it is similar to the 1D array.

In [ ]:
# Let y = np.array([[1, 4, 3],[9, 2, 7]])
# Get the element at first row and 2nd column of array y.
print(y[0,1])

4


In [ ]:
# Let y = np.array([[1, 4, 3],[9, 2, 7]])
# Get the first row of array y.
print(y[0,:])

[1 4 3]


In [ ]:
# Let y = np.array([[1, 4, 3],[9, 2, 7]])
# Get the last column of array y.
print(y[:,-1])

[3 7]


In [ ]:
# Let y = np.array([[1, 4, 3],[9, 2, 7]])
# Get the first and third column of array y.
print(y[:, [0, 2]])

[[1 3]
 [9 7]]


In [ ]:
# There are some predefined arrays that are really useful.
# For example:
# the np.zeros, np.ones, and np.empty are 3 useful functions.
# Let’s see the examples.

In [ ]:
# Generate a 5 by 3 array with all the elements as 0.
A = np.zeros((5,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#  Generate a 3 by 5 array with all the elements as 1.
B = np.ones((3, 5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# NOTE! The shape of the array is defined in a tuple
# with row as the first item, and column as the second.
# If you only need a 1D array,
# then it could be only one number as the input: np.ones(3).

In [ ]:
# Generate a 1D empty array with 3 elements.
C = np.empty(3)
print(C)

[4.9e-324 2.0e-323 1.5e-323]


In [ ]:
# NOTE! The empty array is not really empty,
# it is filled with random very small numbers.

In [ ]:
# You can reassign a value of an array by
# using array indexing and the assignment operator.
# You can reassign multiple elements to a single number
# using array indexing on the left side.
# You can also reassign multiple elements of an array
# as long as both the number of elements
# being assigned and the number of elements assigned is the same.
# You can create an array using array indexing.

In [ ]:
# Ex:
# Let a = [1, 2, 3, 4, 5, 6].
# Reassign the fourth element of a to 7.
a = np.arange(1,7)
a[3] = 7
print(a)

[1 2 3 7 5 6]


In [ ]:
# Reassign the first, second, and thrid elements to 1.
a[:3] = 1
print(a)

[1 1 1 7 5 6]


In [ ]:
# Reassign the second, third, and fourth elements to 9, 8, and 7.
a[1:4] = [9, 8, 7]
print(a)

[1 9 8 7 5 6]


In [ ]:
# Ex: Create a zero array b with shape 2 by 2,
# set b=np.array([[1,2],[3,4]]) using array indexing
b = np.zeros((2,2))
print(b)
b[0,0]=1
b[0,1]=2
b[1,0]=3
b[1,1]=4
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 2.]
 [3. 4.]]


In [ ]:
# Ex: Create a zero array b with shape 2 by 2,
# set b=np.array([[1,2],[3,4]]) using array indexing
b = np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


In [ ]:
b[0,:]=[1,2]
b[1,:] = [3,4]
print(b)

[[1. 2.]
 [3. 4.]]


In [ ]:
b = np.zeros((2,2))
b[:,0]=[1,3]
b[:,1] = [2,4]
print(b)

[[1. 2.]
 [3. 4.]]


In [ ]:
# Basic arithmetic is defined for arrays.
# However, there are operations between
# a scalar (a single number) and an array and
# operations between two arrays.
# We will start with operations between a scalar and an array.
# To illustrate, let c be a scalar, and b be a matrix.

In [ ]:
# b + c adds c to every element of b
# b − c subtracts c from every element of b
# b * c multiplies every element of b by c
# and b / c divides every element of b by c

In [ ]:
# Ex: Let b = np.array([[1,2],[3,4]])
# Add and substract 2 from b. Multiply and divide b by 2.
# Square every element of b.
# Let c be a scalar.  verify that:
# b + c = c + b and cb = bc.

In [ ]:
# Add 2 to b
b = np.array([[1,2],[3,4]])
b + 2

array([[3, 4],
       [5, 6]])

In [ ]:
# Substract 2 from b
b = np.array([[1,2],[3,4]])
b - 2

array([[-1,  0],
       [ 1,  2]])

In [ ]:
# Multiply b by 2
b = np.array([[1,2],[3,4]])
b*2

array([[2, 4],
       [6, 8]])

In [ ]:
# Divide b by 2
b = np.array([[1,2],[3,4]])
b/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
#Square every element of b
b = np.array([[1,2],[3,4]])
b[0,0]=b[0,0]**2
b[0,1]=b[0,1]**2
b[1,0]=b[1,0]**2
b[1,1]=b[1,1]**2
b

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
#Square every element of b
b = np.array([[1,2],[3,4]])
b**2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
# verify that:  b + c = c + b and cb = bc.
b = np.array([[1,2],[3,4]])
c=8
b + c == c + b

array([[ True,  True],
       [ True,  True]])

In [ ]:
# verify that:  cb = bc.
b = np.array([[1,2],[3,4]])
c=8
b*c == c*b

array([[ True,  True],
       [ True,  True]])

In [ ]:
# Describing operations between two matrices is more complicated.
# Let b and d be two matrices of the same size.
# b − d takes every element of b and subtracts
# the corresponding element of d.
# Similarly, b + d adds every element of d
# to the corresponding element of b.

In [ ]:
# Let b = np.array([[1,2],[3,4]]) and
# d = np.array([[3,4],[5,6]]).
# Compute b - d and b + d
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])
b + d

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])
b - d

array([[-2, -2],
       [-2, -2]])

In [ ]:
# There are two different kinds of matrix multiplication (and division).
# There is element-by-element matrix multiplication
# and standard matrix multiplication.
# For this section, we will only show how
# element-by-element matrix multiplication and division work.
# Standard matrix multiplication will be described later.
# Python takes the * symbol to mean element-by-element multiplication.
# For matrices b and d of the same size,
# b * d takes every element of b and multiplies it
# by the corresponding element of d.
# The same is true for / and **.

In [ ]:
# Ex: Compute b * d, b / d, and b**d.
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [ ]:
b*d

array([[ 3,  8],
       [15, 24]])

In [ ]:
b/d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [ ]:
b**d

array([[   1,   16],
       [ 243, 4096]])

In [ ]:
# The transpose of an array, b, is an array, d,
# where b[i, j] = d[j, i].
# In other words, the transpose switches
# the rows and the columns of b.
# You can transpose an array in Python using the array method T.

In [ ]:
# Ex: Compute the transpose of array b.
b = np.array([[1, 2], [3, 4]])
b.T

array([[1, 3],
       [2, 4]])

In [ ]:
# Numpy has many arithmetic functions, such as sin, cos, etc.,
# can take arrays as input arguments.
# The output is the function evaluated for
# every element of the input array.
# A function that takes an array as input and
# performs the function on it is said to be vectorized.

In [ ]:
#  Compute np.sqrt for x = [1, 4, 9, 16].
x=np.array([1,4,9,16])
np.sqrt(x)

array([1., 2., 3., 4.])

In [ ]:
y=[1,4,9,16]
np.sqrt(y)

array([1., 2., 3., 4.])

In [ ]:
# Logical operations are only defined between
# a scalar and an array and between two arrays of the same size.
# Between a scalar and an array,
# the logical operation is conducted between
# the scalar and each element of the array.
# Between two arrays, the logical operation
# is conducted element-by-element.

In [ ]:
# Ex:
# Check which elements of the array x = [1, 2, 4, 5, 9, 3]
# are larger than 3.
x = np.array([1, 2, 4, 5, 9, 3])
x > 3

array([False, False,  True,  True,  True, False])

In [ ]:
# Ex:
# Check which elements in x=[1, 2, 4, 5, 9, 3]
# are larger than the corresponding
# element in y = [0, 2, 3, 1, 2, 3].
y = np.array([0, 2, 3, 1, 2, 3])
x > y

array([ True, False,  True,  True,  True, False])

In [ ]:
# Python can index elements of an array that satisfies a logical expression.

In [ ]:
# Ex:
# Let x be the same array as in the previous example.
# Create a variable y that contains all
# the elements of x that are strictly bigger than 3.
# Assign all the values of x that are bigger than 3, the value 0.

In [ ]:
x = np.array([1, 2, 4, 5, 9, 3])
# Create a variable y that contains all the elements of x that
# are strictly bigger than 3.
y = x[x>3]
y

array([4, 5, 9])

In [ ]:
# Assign all the values of x that are bigger than 3, the value 0.
x[x>3]=0
x

array([1, 2, 0, 0, 0, 3])

**Some Useful Functions on Numpy Arrays**

Each of these functions takes an array as an argument and returns a single value.


**Function** $\hspace{1.7in}$            **Description**

np.prod $\hspace{1.7in}$ 	Multiply all elements together

np.sum $\hspace{1.7in}$ Add all elements together

np.all $\hspace{1.8in}$ Test whether all elements are true values (non-zero numbers are true)

np.any$ \hspace{1.8in}$ Test whether any elements are true values (non-zero numbers are true)

np.count_nonzero $\hspace{.9in}$ Count the number of non-zero elements

In [ ]:
# Function              Description
# np.diff               Difference between adjacent elements
# np.round              Round each number to the nearest integer (whole number)
# np.cumprod            A cumulative product: for each element, multiply all elements so far
# np.cumsum 	          A cumulative sum: for each element, add all elements so far
# np.exp                Exponentiate each element
# np.log                Take the natural logarithm of each element
# np.sqrt               Take the square root of each element
# np.sort               Sort the elements

 **Ranges**

A range is an array of numbers in increasing or decreasing order, each separated by a regular interval. Ranges are useful in a surprisingly large number of situations, so it's worthwhile to learn about them.

Ranges are defined using the *np.arange* function, which takes either one, two, or three arguments: a start, and end, and a 'step'.

If you pass one argument to np.arange, this becomes the end value, with start=0, step=1 assumed. Two arguments give the start and end with step=1 assumed. Three arguments give the start, end and step explicitly.

A range always includes its start value, but does not include its end value. It counts up by step, and it stops before it gets to the end.

In [ ]:
# np.arange(end): An array starting with 0 of increasing
# consecutive integers, stopping before end.

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

Notice how the array starts at 0 and goes only up to 4, not to the end value of 5.

In [ ]:
# np.arange(start, end): An array of consecutive increasing
# integers from start, stopping before end.

In [ ]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [ ]:
# np.arange(start, end, step): A range with a difference of step
# between each pair of consecutive values,
# starting from start and stopping before end.

In [ ]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

This array starts at 3, then takes a step of 5 to get to 8, then another step of 5 to get to 13, and so on.

When you specify a step, the start, end, and step can all be either positive or negative and may be whole numbers or fractions.

In [ ]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

Example: Leibniz's formula for $\pi$

The great German mathematician and philosopher Gottfried Wilhelm Leibniz (1646 - 1716) discovered a wonderful formula for an infinite sum of simple fractions. The formula is
$$\pi=4\cdot\large\left(1 - \frac{1}{3} + \frac{1}{5}-\frac{1}{7}+\frac{1}{9}-\frac{1}{11}+\cdots\large\right)$$

Though some math is needed to establish this, we can use arrays to convince ourselves that the formula works. Let's calculate the first 5000 terms of Leibniz's infinite sum and see if it is close to $\pi$.
$$\pi\approx4\cdot\large\left(1 - \frac{1}{3} + \frac{1}{5}-\frac{1}{7}+\frac{1}{9}-\frac{1}{11}+\cdots-\frac{1}{9999}\large\right)$$

We will calculate this finite sum by adding all the positive terms first and then subtracting the sum of all the negative terms

$$4\cdot\large\left(\large\left(1 + \frac{1}{5}+\frac{1}{9}+\cdots+\frac{1}{9997}\large\right)-\large\left(\frac{1}{3}+\frac{1}{7}+\frac{1}{11}+\cdots+\frac{1}{9999}\large\right)\large\right)$$

The positive terms in the sum have 1, 5, 9, and so on in the denominators. The array by_four_to_20 contains these numbers up to 17:

In [ ]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

To get an accurate approximation to $\pi$, we'll use the much longer array positive_term_denominators.

In [ ]:
positive_term_denominators = np.arange(1, 9998, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

The positive terms we actually want to add together are just 1 over these denominators:

In [ ]:
positive_terms = 1 / positive_term_denominators
positive_terms

array([1.00000000e+00, 2.00000000e-01, 1.11111111e-01, ...,
       1.00110121e-04, 1.00070049e-04, 1.00030009e-04])

The negative terms have 3, 7, 11, and so on on in their denominators. This array is just 2 added to positive_term_denominators.

In [ ]:
negative_terms = 1 / (positive_term_denominators + 2)

The overall sum is

In [ ]:
overall_sum = 4 * ( np.sum(positive_terms) - np.sum(negative_terms) )
print(overall_sum)

3.141392653591792


This is very close to $\pi=3.14159....$. Leibniz's formula is looking good!

**Elementwise arithmetic on pairs of numerical arrays**

If an arithmetic operator acts on two arrays of the same size, then the operation is performed on each corresponding pair of elements in the two arrays. The final result is an array.

For example, if array1 and array2 have the same number of elements, then the value of array1 * array2 is an array. Its first element is the first element of array1 times the first element of array2, its second element is the second element of array1 times the second element of array2, and so on.

**Example: Wallis' Formula for $\pi$**

The number $\pi$ is important in many different areas of math. Centuries before computers were invented, mathematicians worked on finding simple ways to approximate the numerical value of $\pi$. We have already seen Leibniz's formula for $\pi$. About half a century before Leibniz, the English mathematician [John Wallis](https://en.wikipedia.org/wiki/John_Wallis) (1616-1703) also expressed $\pi$ in terms of simple fractions, as an infinite product.

$$\pi = 2\cdot\large\left(\frac{2}{1}\cdot\frac{2}{3}\cdot\frac{4}{3}\cdot\frac{4}{5}\cdot\frac{6}{5}\cdot\frac{6}{7}\cdots\large\right)$$

This is a product of “even/odd” fractions. Let's use arrays to multiply a million of them, and see if the product is close to $\pi$.

Multiplication can be done in any order (because approximation to $\pi$ uses only a large finite number of fractions), so we can readjust our calculation to:

$$\pi ≈ 2\cdot\large\left(\frac{2}{1}\cdot\frac{4}{3}\cdot\frac{6}{5}\cdots\frac{1,000,000}{999,999}\large\right)\cdot\large\left(\frac{2}{3}\cdot\frac{4}{5}\cdot\frac{6}{7}\cdots\cdot\frac{1,000,000}{1,000,001}\large\right)$$

We're now ready to do the calculation. We start by creating an array of even numbers 2, 4, 6, and so on up to 1,000,000. Then we create two lists of odd numbers: 1, 3, 5, 7,... up to 999,999, and 3, 5, 7, ... up to 1,000,001.


In [ ]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

Remember that np.prod multiplies all the elements of an array together. Now we can calculate Wallis' product, to a good approximation.

In [ ]:
product = 2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)
print(product)

3.1415910827951143


That's $\pi$ correct to five decimal places. Wallis clearly came up with a great formula

The above can be as well computed as follows

In [ ]:
odd = np.arange(1, 1000000, 2)
one_above_odd = odd + 1
two_above_odd = odd + 2

In [ ]:
product=2 * np.prod(one_above_odd/odd) * np.prod(one_above_odd/two_above_odd)
print(product)

3.1415910827951143
