**Linear Algebra and Systems of Linear Equations**

**Basics of Linear Algebra**

Let's first introduce some basics of linear algebra, which will be used to describe and solve the linear equations.

**Sets**

There are several standard sets related to numbers, for example natural numbers,
whole numbers, integers, rational numbers, irrational numbers, real numbers. A description of each set and the symbol used to denote
them is shown in the following table.

In [ ]:
# Set Name        Symbol    Description
# Naturals        ℕ         ℕ = {1,2,3,4,⋯}
# Wholes          𝕎        𝕎 = ℕ ∪ {0}
# Integers        ℤ         ℤ = 𝕎 ∪ {−1,−2,−3,⋯}
# Rationals       ℚ         ℚ = {𝑝/𝑞:𝑝∈ℤ,𝑞∈ℤ∖{0}}
# Irrationals     𝕀         𝕀 is the set of real numbers not expressible as a fraction of integers.
# Reals           ℝ         ℝ = ℚ ∪ 𝕀

**Ex**

 Let S be the set of all real $(x,y)$ pairs such that $x^2+y^2=1$. Write S using set notation.

$$S=\left\{(x,y):x,y∈ℝ,x^2+y^2=1\right\}$$



**Vectors**

The set $\mathbb{R}^n$ is the set of all $n$-tuples of real numbers. In set notation this is $\mathbb{R}^n=\left\{(x_{1},x_{2},x_{3},\cdots,x_{n}):x_{1},x_{2},\cdots,x_{n}∈ℝ\right\}$. For example, the set $\mathbb{R}^3$ represents the set of real triples, $(x,y,z)$ coordinates, in three-dimensional space.

A **vector** in $\mathbb{R}^n$ is an $n$-tuple, or point, in $\mathbb{R}^n$. Vectors can be written horizontally (i.e., with the elements of the vector next to each other) in a **row vector**, or vertically (i.e., with the elements of the vector on top of each other) in a **column vector**. If the context of a vector is ambiguous, it usually means the vector is a column vector. The $i$-th element of a vector, $v$, is denoted by $v_{i}$. The transpose of a column vector is a row vector of the same length, and the transpose of a row vector is a column vector. In mathematics, the transpose is denoted by a superscript $T$, or $v^{T}$. The **zero vector** is the vector in $\mathbb{R}^n$ containing all zeros.

The **norm** of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). The most common is called the $L_{2}$ norm, which is computed according to the distance formula you are probably familiar with from grade school. The $L_{2}$ norm of a vector $v$ is denoted by $\Vert v \Vert_{2}$
 and $\Vert v \Vert_{2}=\sqrt{\sum_{i}v^{2}_{i}}$. This is sometimes also called Euclidian length and refers to the “physical” length of a vector in one-, two-, or three-dimensional space. The $L_{1}$ norm, or “Manhattan Distance,” is computed as $\Vert v \Vert_{1}=\sum_{i}|{v_{i}}|$, and is named after the grid-like road structure in New York City. In general, the $\mathbf{p}$-**norm**, $L_{p}$
, of a vector is $\Vert v \Vert_{p}=\sqrt[p]{\sum_{i}{|v^{p}_{i}|}}$
. The $L_{\infty}$ norm is the $p$-norm, where $p=\infty$. The $L_{\infty}$
 norm is written as $\Vert v \Vert_{\infty}$ and it is equal to the maximum absolute value in $v$.

In [1]:
# Ex: Create a row vector and column vector, and show the shape of the vectors.
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
print(vector_row)
vector_column = np.array([[1],[2], [3],[4]])
print(vector_column)

[[ 1 -5  3  2  4]]
[[1]
 [2]
 [3]
 [4]]


In [2]:
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


Transpose the row vector we defined above into a column vector and
calculate the $L_{1}$, $L_{2}$, and $L_{\infty}$ norms.

In [3]:
from numpy.linalg import norm
vector_row_T = vector_row.T
print(vector_row_T)


[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]


In [4]:
vector_row = np.array([[1, -5, 3, 2, 4]])

In [5]:
norm_1 = norm(vector_row_T,1)
norm_2 = norm(vector_row_T,2)
norm_inf = norm(vector_row_T,np.inf)
print('L_1 is: {:.1f}'.format(norm_1))
print('L_2 is: {:.1f}'.format(norm_2))
print('L_inf is: {:.1f}'.format(norm_inf))

L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


In [6]:
# The result is the same passing
# the column vector vector_column = np.array([[1],[-5], [3],[2],[4]])
from numpy.linalg import norm
vector_column = np.array([[1],[-5], [3],[2],[4]])
#print(vector_row_T)
norm_1 = norm(vector_column,1)
norm_2 = norm(vector_column,2)
norm_inf = norm(vector_column,np.inf)
print('L_1 is: {:.1f}'.format(norm_1))
print('L_2 is: {:.1f}'.format(norm_2))
print('L_inf is: {:.1f}'.format(norm_inf))

L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


In [7]:
# The result is the same as well passing the one dimensional
# array to the norm function
from numpy.linalg import norm
vector = np.array([1, -5, 3, 2, 4])
#print(vector_row_T)
norm_1 = norm(vector,1)
norm_2 = norm(vector,2)
norm_inf = norm(vector,np.inf)
print('L_1 is: {:.1f}'.format(norm_1))
print('L_2 is: {:.1f}'.format(norm_2))
print('L_inf is: {:.1f}'.format(norm_inf))

L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


**Vector addition**

It is defined as the pairwise addition of each of the elements of the added vectors. For example, if $v$ and $w$ are vectors in $\mathbb{R}^n$, then $u=v+w$
 is defined as $u_{i}=v_{i}+w_{i}$.

**Vector multiplication**

It can be defined in several ways depending on the context. Scalar multiplication of a vector is the product of a vector and a scalar (i.e., a number in $\mathbb{R}$). Scalar multiplication is defined as the product of each element of the vector by the scalar. More specifically, if $\alpha$ is a scalar and $v$ is a vector, then $u=\alpha v$ is defined as $u_{i}=\alpha v_{i}$. Note that this is exactly how Python implements scalar multiplication with a vector.

Show that $a(v+w)=av+aw$ (i.e., scalar multiplication of a vector distributes across vector addition).

By vector addition, $u=v+w$ is the vector with $u_{i}=v_{i}+w_{i}$. By scalar multiplication of a vector, $x=a u$ is the vector with $x_{i}=a(v_{i}+w_{i})$. Since $a$, $v_{i}$, and $w_{i}$ are scalars, multiplication distributes and $x_{i}=a v_{i}+a w_{i}$. Therefore, $a(v+w)=av+aw$.



The **dot product** of two vectors is the sum of the product of the respective elements in each vector and is denoted by $\cdot$, and $v\cdot w$ is read “v dot w.” Therefore for $v$ and $w$ $\in \mathbb{R}^n$, $d=v\cdot w$ is defined as $d=\sum_{i}^{n}v_{i}w_{i}$. The **angle between two vectors**, $\theta$, is defined by the formula:
$$v\cdot w=\Vert v \Vert_{2}\Vert w \Vert_{2}\cos\theta$$
The dot product is a measure of how similarly directed the two vectors are. For example, the vectors $(1,1)$ and $(2,2)$ are parallel. If you compute the angle between them using the dot product, you will find that $\theta=0$. If the angle between the vectors, $\theta=\pi/2$, then the vectors are said to be perpendicular or orthogonal, and the dot product is $0$.

Compute the angle between the vectors $v=[10,9,3]$ and $w=[2,5,12]$.

In [8]:
from numpy import arccos, dot
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
# arccos produces angles in radians
print(theta)
# Convert angle from radian to degree:
print((180/np.pi)*theta)

[[0.97992471]]
[[56.14555015]]


Finally, the **cross product** between two vectors, $v$ and $w$, is written $v\times w$. It is defined by $v\times w=\Vert v \Vert_{2}\Vert w \Vert_{2}\sin(\theta) n$, where $\theta$ is the angle between the $v$ and $w$ (which can be computed from the dot product) and $n$ is a vector perpendicular to both $v$
 and $w$ with unit length (i.e., the length is one). The geometric interpretation of the cross product is a vector perpendicular to both $v$
 and $w$ with length equal to the area enclosed by the parallelogram created by the two vectors.

Given the vectors $v=[0,2,0]$ and $w=[3,0,0]$, use the Numpy function cross to compute the cross product of $v$ and $w$.

In [9]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


Assuming that S is a set in which addition and scalar multiplication are defined, a **linear combination** of S is defined as $∑\alpha_{i}s_{i},$
where $\alpha_{i}$ is any real number and $s_{i}$ is the $i$-th object in S. Sometimes the $\alpha_{i}$ values are called the coefficients of $s_{i}$. Linear combinations can be used to describe numerous things. For example, a grocery bill can be written $\sum c_{i}n_{i}$, where $c_{i}$ is the cost of item $i$ and $n_{i}$ is the number of item $i$ purchased. Thus, the total cost is a linear combination of the items purchased.

A set is called **linearly independent** if no object in the set can be written as a linear combination of the other objects in the set. For the purposes of this book, we will only consider the linear independence of a set of vectors. A set of vectors that is not linearly independent is **linearly dependent**.

Given the row vectors $v=[0,3,2]$, $w=[4,1,1]$, and $u=[0,−2,0]$
, write the vector $x=[−8,−1,4]$ as a linear combination of $v$, $w$, and $u$.

In [10]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v -2*w + 4*u
print(x)

[[-8 -1  4]]


Determine by inspection whether the following set of vectors is linearly independent: $v=[1,1,0]$, $w=[1,0,0]$, $u=[0,0,1]$.

Clearly $u$ is linearly independent from $v$ and $w$ because only $u$
 has a nonzero third element. The vectors $v$ and $w$ are also linearly independent because only $v$ has a nonzero second element. Therefore, $v$, $w$, and $u$ are linearly independent.



**Matrices**

An $m\times n$ matrix is a rectangular table of numbers consisting of $m$ rows and $n$ columns. The norm of a matrix can be considered as a particular kind of vector norm, if we treat the $m\times n$  elements of $M$ as the elements of an $mn$ dimensional vector, then the p-norm of this vector can be written as:
$$\Vert M \Vert_{p}=\sqrt[p]{\sum_{i}^{m}\sum_{j}^{n}|a_{ij}|^{p}}$$
You can calculate the matrix norm using the same norm function in Numpy as that for vector.

Matrix addition and scalar multiplication for matrices work the same way as for vectors. However, **matrix multiplication** between two matrices, $P$ and $Q$, is defined when $P$ is an $m\times p$ matrix and $Q$ is a $p\times n$ matrix. The result of $M=PQ$ is a matrix $M$ that is $m\times n$. The dimension with size $p$ is called the inner matrix dimension, and the inner matrix dimensions must match (i.e., the number of columns in $P$ and the number of rows in $Q$
must be the same) for matrix multiplication to be defined. The dimensions $m$
and $n$ are called the outer matrix dimensions. Formally, if $P$ is $m\times p$
and $Q$ is $p\times n$, then $M=PQ$ is defined as
$$M_{ij}=\sum_{k=1}^{p}P_{ik}Q_{kj}$$
The product of two matrices $P$ and $Q$ in Python is achieved by using the dot method in Numpy. The transpose of a matrix is a reversal of its rows with its columns. The transpose is denoted by a superscript, $T$, such as $M.T$ is the transpose of matrix $M$. In Python, the method $T$ for a Numpy array is used to get the transpose. For example, if $M$
 is a matrix, then $M.T$ is its transpose.

 Let the Python matrices $P=[[1,7],[2,3],[5,0]]$ and $Q=[[2,6,3,1],[1,2,3,4]]$. Compute the matrix product of $P$ and $Q$.

In [11]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


Show that the product of $Q$ and $P$
 will produce an error.

In [12]:
print(np.dot(Q, P))

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

A square matrix is an $n\times n$ matrix; that is, it has the same number of rows as columns. The determinant is an important property of square matrices. The determinant is denoted by $det(M)$, both in mathematics and in Numpy's linalg package, sometimes it is also denoted as |M|.

Recall formulas for detrminants of a $2\times 2$ and $3\times 3$ matrices.

The identity matrix is a square matrix with ones on the diagonal and zeros elsewhere. The identity matrix is usually denoted by $I$, and is analagous to the real number identity, $1$. That is, multiplying any matrix by $I$
 (of compatible size) will produce the same matrix.

 Use Python to find the determinant of the matrix
 $ M=[[0,2,1,3],[3,2,8,1],[1,0,0,3],[0,3,2,1]]$.

In [13]:
from numpy.linalg import det

M = np.array([[0,2,1,3],
             [3,2,8,1],
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: {:.1f}'.format(det(M)))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0


Use the np.eye function to produce a $4\times 4$ identity matrix, $I$. Multiply $M$ by $I$ to show that the result is $M$.

In [14]:
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


The inverse of a square matrix $M$ is a matrix of the same size, $N$, such that $M\cdot N=I$. The inverse of a matrix is analagous to the inverse of real numbers. For example, the inverse of $3$ is $\dfrac{1}{3}$ because $3\cdot \dfrac{1}{3}=1$. A matrix is said to be invertible if it has an inverse. The inverse of a matrix is unique; that is, for an invertible matrix, there is only one inverse for that matrix. If $M$ is a square matrix, its inverse is denoted by $M^{-1}$ in mathematics, and it can be computed in Python using the function inv from Numpy's linalg package.

Formula for the inverse of a $2\times 2$ matrix.

The calculation of the matrix inverse for the analytic solution becomes complicated with increasing matrix dimension, there are many other methods that can make things easier, such as Gaussian elimination, Newton's method, Eigendecomposition and so on. We will introduce some of these methods after we learn how to solve a system of linear equations, because the process is essentially the same.

Recall that $0$ has no inverse for multiplication in the real-numbers setting. Similarly, there are matrices that do not have inverses. These matrices are called singular. Matrices that do have an inverse are called nonsingular.

One way to determine if a matrix is singular is by computing its determinant. If the determinant is $0$, then the matrix is singular; if not, the matrix is nonsingular.

The matrix $M$ (in the previous example) has a nonzero determinant. Compute the inverse of $M$.

In [15]:
from numpy.linalg import inv
print('Inv M:\n', inv(M))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


Show that the matrix $P=[[0,1,0],[0,0,0],[1,0,1]]$ has a determinant value of $0$ and therefore has no inverse.

In [16]:
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))

det(p):
 0.0


In [17]:
a = np.array([[1,2],[3,4]])
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

A matrix that is close to being singular (i.e., the determinant is close to $0$) is called ill-conditioned. Although ill-conditioned matrices have inverses, they are problematic numerically in the same way that dividing a number by a very, very small number is problematic. That is, it can result in computations that result in overflow, underflow, or numbers small enough to result in significant round-off errors. The condition number is a measure of how ill-conditioned a matrix is, and it can be computed using Numpy's function $\verb|cond|$ from linalg. The higher the condition number, the closer the matrix is to being singular.

The rank of an $m\times n$ matrix $A$ is the number of linearly independent columns or rows of $A$, and is denoted by rank($A$). It can be shown that the number of linearly independent rows is always equal to the number of linearly independent columns for any matrix. A matrix is called **full row rank** or **full column rank** if rank ($A$)=min(m,n). The matrix, $A$, is called full rank if all of its columns are linearly independent and $A$ is a square matrix (that is $m=n$). An augmented matrix is a matrix, $A$, concatenated with a vector, $y$, and is written $[A,y]$. This is commonly read “$A$
 augmented with $y$.” You can use $\verb|np.concatenate|$ to concatenate them. If $rank([A,y])=rank($A$)+1$, then the vector, $y$, is “new” information. That is, it cannot be created as a linear combination of the columns in $A$. The rank is an important property of matrices because of its relationship to solutions of linear equations.

Given matrix $A=[[1,1,0],[0,1,0],[1,0,1]]$, compute the condition number and rank for this matrix.

In [18]:
import numpy as np
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

#print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))

Rank:
 3


If $y=[[1],[2],[1]]$, get the augmented matrix [A, y].

In [19]:
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])
y = np.array([[1], [2], [1]]) # y is a column vector
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


Add the vector $y=[[1,2,1]]$ to the last row of the matrix $A$.

In [20]:
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])
y=np.array([[1,2,1]]) # y is a row vector
A_y = np.concatenate((A, y), axis = 0)
A_y

array([[1, 1, 0],
       [0, 1, 0],
       [1, 0, 1],
       [1, 2, 1]])

**Systems of Linear Equations**

A **linear equation** is an equality of the form $\sum_{i}^{n}a_{i}x_{i}=y$, where $a_i$'s are scalars, $x_i$'s are unknown variables in $\mathbb{R}$, and $y$ is a scalar.

A **systems of Linear Equations** is a set of linear equations that share the same variables.  Consider the following system of linear equations:

$$\begin{cases}
a_{1,1}x_{1} &+& a_{1,2}x_{2} &+& \cdots &+& a_{1,n-1}x_{n-1}&+&a_{1,n}x_{n}&=&y_{1}\\
a_{2,1}x_{1} &+& a_{2,2}x_{2} &+& \cdots &+& a_{2,n-1}x_{n-1}&+&a_{2,n}x_{n}&=&y_{2}\\
a_{m-1,1}x_{1} &+& a_{m-1,2}x_{2} &+& \cdots &+& a_{m-1,n-1}x_{n-1}&+&a_{m-1,n}x_{n}&=&y_{m-1}\\
&& & &\cdots&\\
a_{m,1}x_{1} &+& a_{m,2}x_{2} &+& \cdots &+& a_{m,n-1}x_{n-1}&+&a_{m,n}x_{n}&=&y_{m}
\end{cases}
$$

where$a_{i,j}$ and $y_{j}$ are real numbers. The matrix form of a system of linear equations is $A\textbf{x = y}$ where $A$ is an $m\times n$ matrix,
$A(i,j)=a_{i,j}$ ,$y$ is a vector in $\mathbb{R}^{m}$, and $x$ is an unknown vector in $\mathbb{R}^{n}$. The matrix form is showing as below:

$$
\begin{bmatrix}
a_{1,1}       &   a_{1,2}        & \dots     &   a_{1,n}       \\
a_{2,1}        &   a_{2,2}        & \dots     &   a_{2,n}        \\
\vdots  &  \vdots   &   \vdots  &   \vdots  \\   
a_{m,1}        &   a_{m,2}        & \dots     &   a_{m,n}        \\
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2     \\
\vdots  \\
x_n     \\
\end{bmatrix}
    =
\begin{bmatrix}
y_1     \\
y_2     \\
\vdots  \\
y_m     \\
\end{bmatrix}
$$

Put the following system of equations into matrix form.

$$\begin{cases}
4x &+& 3y &-& 5z &=&2\\
-2x &-& 4y &+& 5z&=&5\\
 && 7x &+& 8y&=&-3\\
 && x &+& 2z&=&1\\
9x &+& y &-& 6z&=&6
\end{cases}
$$
The associated matrix form is:
$$
\begin{bmatrix}
4      &   3        &  -5      \\
-2        &   -4        & 5       \\
7& 8   &   0 \\   
1& 0   &   2 \\   
9& 1   &   -6 \\   
\end{bmatrix}
\begin{bmatrix}
x     \\
y    \\
z    \\
\end{bmatrix}
    =
\begin{bmatrix}
2     \\
5     \\
-3  \\
1     \\
6
\end{bmatrix}
$$

**Solutions to Systems of Linear Equations**

Consider a system of linear equations in matrix form, $Ax=y$, where $A$ is an $m\times n$ matrix. Recall that this means there are $m$ equations and $n$ unknowns in our system. A solution to a system of linear equations is an $x$ in $\mathbb{R}^{n}$ that satisfies the matrix form equation. Depending on the values that populate $A$ and $y$, there are three distinct solution possibilities for $x$. Either there is no solution for $x$, or there is one, unique solution for $x$, or there are an infinite number of solutions for $x$.

**Case 1**: There is no solution for $x$. If $rank([𝐴,𝑦])=rank($A$)+1$, then $y$ is linearly independent from the columns of $A$. Therefore $y$ is not in the range of $A$ and by definition, there cannot be an $x$ that satisfies the equation. Thus, comparing rank($[𝐴,𝑦]$) and rank($A$) provides an easy way to check if there are no solutions to a system of linear equations.

**Case 2**: There is a unique solution for $x$. If rank($[𝐴,𝑦]$)=rank($A$), then $y$ can be written as a linear combination of the columns of $A$ and there is at least one solution for the matrix equation. For there to be only one solution, rank($A$)=$n$ must also be true. In other words, the number of equations must be exactly equal to the number of unknowns. To see why this property results in a unique solution, consider the following three relationships between $m$ and $n$ :$m < n$ , $m=n$, and $m > n$.

*   For the case where $m < n$, rank($A$)=$n$ cannot possibly be true because this means we have a “fat” matrix with fewer equations than unknowns. Thus, we do not need to consider this subcase.
*   When $m=n$ and rank($A$)=$n$, then $A$ is square and invertible. Since the inverse of a matrix is unique, then the matrix equation $Ax=y$ can be solved by multiplying each side of the equation, on the left, by $A^{-1}$. This results in $A^{-1}Ax=A^{-1}y→Ix=A^{-1}y→x=A^{-1}y$, which gives the unique solution to the equation.

*   If $m > n$, then there are more equations than unknowns. However if rank($A$)=$n$, then it is possible to choose $n$ equations (i.e., rows of $A$) such that if these equations are satisfied, then the remaining $m-n$ equations will be also satisfied. In other words, they are redundant. If the $m-n$ redundant equations are removed from the system, then the resulting system has an $A$ matrix that is $n\times n$, and invertible. These facts are not proven in this text. The new system then has a unique solution, which is valid for the whole system.





**Case 3**: There is an infinite number of solutions for $x$. If rank($[𝐴,𝑦]$)=rank($A$), then $y$ is in the range of $A$, and there is at least one solution for the matrix equation. However, if rank($A$) < $n$, then there is an infinite number of solutions. The reason for this fact is as follows: although it is not shown here, if rank($A$) < $n$, then there is at least one nonzero vector, $z$, that is in the null space of $A$ (Actually there are an infinite number of null space vectors under these conditions.). If $z$ is in the nullspace of $A$, then $Az=0$ by definition. Now let $x^{*}$ be a solution to the matrix equation $Ax=y$; then necessarily, $Ax^{*}=y$. However, $Ax^{*}+Az=y$ or $A(x^{*}+z)=y$. Therefore, $x^{*}+z$ is also a solution for $Ax=y$. In fact, since $A$ is a linear transformation, $x^{*}+\alpha z$ is a solution for any real number, $\alpha$ (you should try to show this on your own). Since there are an infinite number of acceptable values for $\alpha$, there are an infinite number of solutions for the matrix equation.

In the rest of the chapter, we will only discuss how we solve a systems of equations when it has unique solution. We will discuss some of the common methods that you often come across in your work in this section. And in the next section, we will show you how to solve it in Python.

Let's say we have $n$ equations with $n$ variables, $Ax=y$, as shown in the following:
$$
\begin{bmatrix}
a_{1,1}       &   a_{1,2}        & \dots     &   a_{1,n}       \\
a_{2,1}        &   a_{2,2}        & \dots     &   a_{2,n}        \\
\vdots  &  \vdots   &   \vdots  &   \vdots  \\   
a_{n,1}        &   a_{n,2}        & \dots     &   a_{n,n}        \\
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2     \\
\vdots  \\
x_n     \\
\end{bmatrix}
    =
\begin{bmatrix}
y_1     \\
y_2     \\
\vdots  \\
y_n     \\
\end{bmatrix}
$$

In [21]:
A = np.array([[4,3,-5],[-2,-4,5],[0,7,8],[1,0,2],[9,1,-6]])
y = np.array([[2], [5], [-3],[1],[6]]) # y is a column vector
A_y = np.concatenate((A, y), axis = 1)
print(matrix_rank(A))
print(matrix_rank(A_y))
# Ax=y has no solution

3
4


**Gauss Elimination Method**

The Gauss Elimination method is a procedure to turn matrix $A$ into an upper triangular form to solve the system of equations. Let's use a system of $4$ equations and $4$ variables to illustrate the idea. The Gauss Elimination essentially turning the system of equations to:
$$
\begin{bmatrix}
a_{1,1}       &   a_{1,2}        &  a_{1,3}    &   a_{1,4}       \\
0        &   a^{\prime}_{2,2}        & a^{\prime}_{2,3}    &   a^{\prime}_{2,4}        \\
0        &   0        & a^{\prime}_{3,3}    &   a^{\prime}_{3,4}        \\
0        &   0        & 0    &   a^{\prime}_{4,4}        \\
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2     \\
x_3     \\
x_4    \\
\end{bmatrix}
    =
\begin{bmatrix}
y^{\prime}_1     \\
y^{\prime}_2     \\
y^{\prime}_3     \\
y^{\prime}_4     \\
\end{bmatrix}
$$
By turning the matrix form into this, we can see the equations turn into:
$$\begin{cases}
a_{1,1}x_1  &+& a_{1,2}x_2  &+&  a_{1,3}x_3 &+& a_{1,4}x_4  &=&y^{\prime}_1 \\
&& a^{\prime}_{2,2}x_2 &+&  a^{\prime}_{2,3}x_3 &+& a^{\prime}_{2,4}x_4  &=&y^{\prime}_2 \\
&&&&  a^{\prime}_{3,3}x_3 &+& a^{\prime}_{3,4}x_4  &=&y^{\prime}_3 \\
&&&&&&  a^{\prime}_{4,4}x_4  &=&y^{\prime}_4
\end{cases}
$$

We can see by turning into this form, $x_{4}$ can be easily solved by dividing both sides by $a^{\prime}_{4,4}$, then we can back substitute it into the 3rd equation to solve $x_3$. With $x_3$ and $x_4$, we can substitute them to the 2nd equation to solve $x_2$. Finally, we can get all the solution for $x$. We solve the system of equations from bottom-up, this is called backward substitution. Note that, if $A$ is a lower triangular matrix, we would solve the system from top-down by forward substitution.


Let's work on an example to illustrate how we solve the equations using Gauss Elimination. Use Gauss Elimination to solve the following equations.
$$\begin{cases}
4x_1  &+& 3x_2  &-&  5x_3 &=2 \\
-2x_1  &-& 4x_2  &+&  5x_3 &=5 \\
&& 8x_1  &+&  8x_2 &=-3
\end{cases}
$$

**Gauss-Jordan Elimination Method**

Gauss-Jordan Elimination solves the systems of equations using a procedure to turn $A$ into a diagonal form, such that the matrix form of the equations becomes

$$
\begin{bmatrix}
1       &   0        &  0    &   0       \\
0        &   1        & 0    &   0        \\
0        &   0        & 1    &   0       \\
0        &   0        & 0    &   1        \\
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2     \\
x_3     \\
x_4    \\
\end{bmatrix}
    =
\begin{bmatrix}
y^{\prime}_1     \\
y^{\prime}_2     \\
y^{\prime}_3     \\
y^{\prime}_4     \\
\end{bmatrix}
$$

 Use Gauss-Jordan Elimination to solve the previous system of equations.

**LU Decomposition Method**

We see the above two methods that involved of changing both $A$ and $y$ at the same time when trying to turn $A$ to an upper triangular or diagonal matrix form. It involves many operations. But sometimes, we may have same set of equations but different sets of $y$ for different experiments. This is actually quite common in the real-world, that we have different experiment observations $y_{a},y_{b},y_{c},\dots$. Therefore, we have to solve $Ax=y_{a}$, $Ax=y_{b}$, $\cdots$ many times, since every time the $[𝐴,𝑦]$ will change. This is really inefficient, is there a method that we only change the left side of $A$ but not the right hand $y$? The LU decomposition method is one of the solution that we only change the matrix $A$ instead of $y$. It has the advantages for solving the systems that have the same coefficient matrices $A$ but different constant vectors $y$.

The LU decomposition method aims to turn $A$ into the multiply of two matrices $L$ and $U$, where $L$ is a lower triangular matrix while $U$ is an upper triangular matrix. With this decomposition, we convert the system of equations to the following form: $LUx=y$. If we define $Ux=z$, then the equations become: $Lz=y$.

We can easily solve the above problem by forward substitution (the opposite of the backward substitution as we saw in Gauss Elimination method). After we solve $z$, we can easily solve the rest of the problem using backward substitution:

But how can we calculate and get the $L$ and $U$ matrices?

Use the previous example to construct the two matrices $L$ and $U$ and solve the system using the $LU$ decomposition.

Use arrays to verify that the $L$ and $U$ matrices found in the previous problem are the LU decomposition of matrix $A$. We should see that $A=LU$.

In [22]:
import numpy as np

U = np.array([[4, 3, -5],
              [0, -2.5, 2.5],
              [0, 0, 12]])
L = np.array([[1, 0, 0],
              [-0.5, 1, 0],
              [2, -0.8, 1]])

print('LU=', np.dot(L, U))

LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


Check that the system
$$\begin{cases}
4x_1  &+& 3x_2  &-&  5x_3 &=2 \\
-2x_1  &-& 4x_2  &+&  5x_3 &=5 \\
&& 8x_1  &+&  8x_2 &=-3
\end{cases}
$$
has a solution.

In [23]:
y = np.array([[2], [5], [-3]]) # y is a column vector
A_y = np.concatenate((np.dot(L, U), y), axis = 1)
print(matrix_rank(A))
print(matrix_rank(A_y))
# Ax=y has solution

3
3


**Iterative Methods**

The above methods we introduced are all direct methods, in which we compute the solution with a finite number of operations. In this section, we will introduce a different class of methods, the **iterative methods**, or **indirect methods**. It starts with an initial guess of the solution and then repeatedly improve the solution until the change of the solution is below a threshold. In order to use this iterative process, we need first write the explicit form of a system of equations. If we have a system of linear equations:
$$
\begin{bmatrix}
a_{1,1}       &   a_{1,2}        & \dots     &   a_{1,n}       \\
a_{2,1}        &   a_{2,2}        & \dots     &   a_{2,n}        \\
\vdots  &  \vdots   &   \vdots  &   \vdots  \\   
a_{n,1}        &   a_{n,2}        & \dots     &   a_{n,n}        \\
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2     \\
\vdots  \\
x_n     \\
\end{bmatrix}
    =
\begin{bmatrix}
y_1     \\
y_2     \\
\vdots  \\
y_n     \\
\end{bmatrix}
$$

we can write its explicit form as:
$$x_{i}=\dfrac{1}{a_{i,i}}\left[y_{i}-\sum^{n}_{j=1,j\ne i}a_{i,j}x_{j}\right]$$

This is the basics of the iterative methods, we can assume initial values for all the $x$, and use it as $x^{(0)}$. In the first iteration, we can substitute $x^{(0)}$ into the right-hand side of the explicit equation above, and get the first iteration solution $x^{(1)}$. Thus, we can substitute $x^{(1)}$ into the equation and get $x^{(2)}$. The iterations continue until the difference between $x^{(k)}$ and $x^{(k-1)}$ is smaller than some pre-defined value.

In order to have the iterative methods work, we do need specific condition for the solution to converge. A sufficient but not necessary condition of the convergence is the coefficient matrix $a$ is a **diagonally dominant** ($|a_{ii}|>\sum_{i\ne j}|a_{ij}|$). This means that in each row of the matrix of coefficients $a$, the absolute value of the diagonal element is greater than the sum of the absolute values of the off-diagonal elements. If the coefficient matrix satisfies the condition, the iteration will converge to the solution. The solution might still converge even when this condition is not satisfied.



**Gauss-Seidel Method**

The **Gauss-Seidel Method** is a specific iterative method, that is always using the latest estimated value for each elements in $x$. For example, we first assume the initial values for $x_{1},x_{2},\cdots,x_{n}$ (except for $x_{1}$), and then we can calculate $x_{1}$. Using the calculated $x_{1}$ and the rest of the $x$ (except for $x_{2}$), we can calculate $x_{2}$. We can continue in the same manner and calculate all the elements in $x$. This will conclude the first iteration. We can see the unique part of Gauss-Seidel method is that we are always using the latest value to calculate the next value in $x$. We can then continue with the iterations until the value converges.

Solve the following system of linear equations using Gauss-Seidel method, use a pre-defined threshold $\epsilon=0.01$. Do remember to check if the convergence condition is satisfied or not.
$$\begin{cases}
8x_1  &+& 3x_2  &-&  3x_3 &=14 \\
-2x_1  &-& 8x_2  &+&  5x_3 &=5 \\
3x_1  &+& 5x_2  &+&  10x_3 &=-8
\end{cases}
$$

Let us first check if the coefficient matrix is diagonally dominant or not.

In [24]:
a = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])

In [25]:
# Find an array of absolute values of diagonal coefficients
diag = np.diag(np.abs(a)) # 1D array
diag

array([ 8,  8, 10])

In [26]:
# Find row sum of the absolute value of the array a
np.sum(np.abs(a), axis=1)

array([14, 15, 18])

In [27]:
# Find row sum without diagonal
off_diag = np.sum(np.abs(a), axis=1) - diag #1D array
off_diag

array([6, 7, 8])

In [28]:
# Conclusion
if np.all( diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')

matrix is diagonally dominant


Since it is guaranteed to converge, we can use Gauss-Seidel method to solve it.

In [29]:
from numpy.linalg import norm
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/(8)
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(10)
    x = np.array([x1, x2, x3])
    # check if it is smaller than threshold
    #dx = np.sqrt(np.dot(x-x_old, x-x_old))
    dx = norm((x - x_old),2)

    #print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    print("{:d}, {:.4f}, {:.4f}, {:.4f}".format(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break

    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

Iteration results
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
Converged!


**Solve Systems of Linear Equations in Python**

Though we discussed various methods to solve the systems of linear equations, it is actually very easy to do it in Python. In this section, we will use Python to solve the systems of equations. The easiest way to get a solution is via the solve function in Numpy.

Use numpy.linalg.solve to solve the following equations.

$$\begin{cases}
4x_1  &+& 3x_2  &-&  5x_3 &=2 \\
-2x_1  &-& 4x_2  &+&  5x_3 &=5 \\
&& 8x_1  &+&  8x_2 &=-3
\end{cases}
$$

In [30]:
import numpy as np

A = np.array([[4, 3, -5],
              [-2, -4, 5],
              [8, 8, 0]])
y = np.array([[2, 5, -3]])

x = np.linalg.solve(A, y.T)
print(x)

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


We can see we get the same results as that in the previous section when we calculated by hand. Under the hood, the solver is actually doing an LU decomposition to get the results. You can check the help of the function, it needs the input matrix to be square and of full-rank, i.e., all rows (or, equivalently, columns) must be linearly independent.

Try to solve the above equations using the matrix inversion approach.

In [31]:
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y.T)
print(x)

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


Find the solution using the previous $LU$ decomposition found by hand.

In [32]:
import numpy as np

U = np.array([[4, 3, -5],
              [0, -2.5, 2.5],
              [0, 0, 12]])
L = np.array([[1, 0, 0],
              [-0.5, 1, 0],
              [2, -0.8, 1]])
y = np.array([[2, 5, -3]])

# Solve Lz_1 = y for z_1
z_1 = np.linalg.solve(L, y.T) # Solution z_1 is in column form
# Solve Ux=z_1
x = np.linalg.solve(U, z_1)

# Print solution
print(x)

[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


We can also get the $L$ and $U$ matrices used in the $LU$ decomposition using the scipy package.

Get the $L$ and $U$ for the above matrix $A$.

In [33]:
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))
print('A=PLU:\n',np.dot(P, np.dot(L, U)))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
A=PLU:
 [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


We can see the $L$ and $U$ we get are different from the ones we got in the last section by hand. You will also see there is a permutation matrix $P$ that returned by the lu function. This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). If you multiply $P$ with $A$, you will see that this permutation matrix reverse the order of the equations for this case.

Multiply $P$ and $A$ and see what's the effect of the permutation matrix on $A$.

In [34]:
print(np.dot(P, A))

[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
