**Eigenvalues and Eigenvectors Problem Statement**

**Eigenvalues and eigenvectors**

A matrix $A$ applied to column vector $x$, that is $Ax$, is a linear transformation of $x$. There is a special transform in the following form:

$$Ax=\lambda x$$
Where $A$ is $n\times n$ matrix, $x$ is $n\times 1$ column vector $(x\ne 0)$, and $\lambda$ is some scalar. Any $\lambda$ that satisfies the above equation is known as an **eigenvalue** of the matrix $A$, while the associated vector $x$ is called an **eigenvector** corresponding to $\lambda$.



**The motivation behind**

The motivation behind the eigenvalues and eigenvectors is that, it helps us to understand the characteristics of the linear transformation, thus make things easy. We know that a vector $x$ can be transformed to a different vector $Ax$ by multiplying $A$. The effect of the transformation represents a scale of the length of the vector and/or the rotate of the vector. The above equation points out that for some vectors, the effect of transformation of $Ax$ is only scale (stretching, compressing, and flipping). The eigenvectors are the vectors that have this property and the eigenvalues $\lambda$'s are the scale factors. Let's look at the following example.

In [ ]:
# Ex:
#  Plot the vector x = [[1], [1]] and the vector b=Ax, where A= [[2, 0], [0, 1]]

In [1]:
plt.style.available

NameError: name 'plt' is not defined

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('seaborn-v0_8-poster')


def plot_vect(x, b, xlim, ylim):

  '''
  function to plot two vectors,
  x - the original vector
  b=Ax - the transformed vector
  xlim - the limit for x
  ylim - the limit for y
  '''
  plt.figure(figsize = (10, 6))
  plt.quiver(0,0,x[0],x[1],\
      color='k',angles='xy',\
      scale_units='xy',scale=1,\
      label='Original vector')
  plt.quiver(0,0,b[0],b[1],\
      color='g',angles='xy',\
      scale_units='xy',scale=1,\
      label ='Transformed vector')
  plt.xlim(xlim)
  plt.ylim(ylim)
  plt.xlabel('X')
  plt.ylabel('Y')
  plt.legend()
  plt.show()

Quiver plots an arrow in the direction of the vector, with the size of the arrow related to the magnitude of the vector. Read more about it [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html).

In [ ]:
A = np.array([[2, 0],[0, 1]])

x = np.array([[1],[1]])
b = np.dot(A, x)
plot_vect(x,b,(0,3),(0,2))

We can see from the generated figure that the original vector $x$ is rotated and stretched longer after transformed by $A$. The vector $[[1], [1]]$ is transformed to $[[2], [1]]$. Let's try to do the same exercise with a different vector $[[1], [0]]$.

In [ ]:
# Ex:
# Plot the vector 𝑥 = [[1], [0]] and the vector b=Ax , where 𝐴 = [[2, 0], [0, 1]]

In [ ]:
x = np.array([[1], [0]])
b = np.dot(A, x)

plot_vect(x,b,(0,3),(-0.5,0.5))

Now we can see that with this new vector, the only thing changed after the transformation is the length of the vector, it is stretched. The new vector is $[[2], [0]]$, therefore, the transform is
$$Ax=2x$$
with $x= [[1], [0]]$ and $\lambda=2$. The direction of the vector doesn't change at all (no rotation). You can also try that $[[0], [1]]$ is another eigenvector.



**The characteristic equation**

In order to get the eigenvalues and eigenvectors, from $Ax=\lambda x$, we can get the following form:
$$(A-\lambda I)x=0$$
where $I$ is the identify matrix with the same dimensions as $A$. If matrix $A-\lambda I$ has an inverse, then multiply both sides with $(A-\lambda I)^{-1}$
, we get a trivial solution $x=0$. Therefore, when $A-\lambda I$
 is singular (no inverse exist), we have a nontrivial solution, which means that the determinant is zero:
 $$\det(A-\lambda I)=0$$
 this equation is called characteristic equation, which will lead to a polynomial equation for $\lambda$, then we can solve for the eigenvalues. Let's look at one example.

In [ ]:
#Ex
# Get the eigenvalues for matrix [[0, 2], [2, 3]]
# Ans: ev1=4, ev2=−1

The characteristic equation gives us:
$$\det
\begin{bmatrix}
0-\lambda     &  2     \\
2       &   3-\lambda    \\  
\end{bmatrix}
=0
$$
Therefore, we have
$$-\lambda(3-\lambda)-4=0⇒\lambda^{2}-3\lambda-4=0$$
We get two eigenvalues:
$$\lambda_{1}=4, \lambda_{2}=-1$$

In [ ]:
# Get the eigenvectors for the above two eigenvalues.

Let's get the first eigenvector when $\lambda_{1}=4$, we can simply insert it back to $A-\lambda I=0$, where we have:
$$
\begin{bmatrix}
-4    &  2     \\
2       &   -1   \\  
\end{bmatrix}
\begin{bmatrix}
x_1     \\
x_2    \\
\end{bmatrix}
=\begin{bmatrix}
0    \\
0    \\
\end{bmatrix}
$$
Therefore, we have two equations $-4x_{1}+2x_{2}=0$ and $2x_{1}-x_{2}=0$, both of them indicate that $x_{2}=2x_{1}$. Therefore, we can have the first eigenvector as
$$x_1=k_1\begin{bmatrix}
1     \\
2    \\
\end{bmatrix}
$$
$k_1$ is a scalar vector $(k_1\ne 0)$, as long as we have the ratio between $x_2$
 and $x_1$ as $2$, it will be an eigenvector. We can verify the vector $[[1], [2]]$ is an eigenvector by inserting it back:
 $$
\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
1     \\
2    \\
\end{bmatrix}
=\begin{bmatrix}
4   \\
8    \\
\end{bmatrix}
=4\begin{bmatrix}
1   \\
2    \\
\end{bmatrix}
$$
By inserting $\lambda=-1$ similarly as above, we can get the other eigenvector as the following, where $k_2\ne 0$:$$ x_2=k_2\begin{bmatrix}
-2   \\
1    \\
\end{bmatrix}
$$

From the above example, we can see how we can get the eigenvalues and eigenvectors from a matrix $A$, and the chosen of the eigenvectors for a system is not unique. But things will become really complicated when you have a larger matrix $A$ and you try to solve the $n^{th}$ order polynomial characteristic equation. Luckily, there are many different numerical methods developed to solve the eigenvalue problems for larger matrices. We will introduce the power method and the $QR$ method.

**The Power Method**

**Find the largest eigenvalue**

In some problems, we only need to find the largest dominant eigenvalue and
its corresponding eigenvector. In this case, we can use the power method -
an iterative method that will converge to the largest eigenvalue.
Let's see in the following how the power method works.

Consider an $n\times n$ matrix $A$ that has $n$ linearly independent real eigenvalues $\lambda_1,\lambda_2,\dots,\lambda_n$ and the corresponding eigenvectors $v_1,v_2,\dots,v_n$. Since the eigenvalues are scalars, we can rank them so that $\lvert\lambda_1\rvert>\lvert\lambda_2\rvert>\dots>\lvert\lambda_n\rvert$ (actually, we only require $\lvert\lambda_1\rvert>\lvert\lambda_2\rvert$, other eigenvalues may be equal to each other).

Because the eigenvectors are independent, they are a set of basis vectors, which means that any vector that is in the same space can be written as a linear combination of the basis vectors. That is, for any vector $x_0$, it can be written as:

$$x_0=c_1v_1+c_2v_2+\dots+c_nv_n$$
where $c_1\ne0$ is the constraint. If it is zero, then we need to choose another initial vector so that $c_1\ne0$.

Now let's multiply both sides by $A$:
$$Ax_0=c_1Av_1+c_2Av_2+\dots+c_nAv_n$$

Since $Av_i=\lambda v_i$, we will have:
$$Ax_0=c_1\lambda_1 v_1+c_2\lambda_2 v_2+\dots+c_n\lambda_n v_n$$
We can change the above equation to:
$$Ax_0=c_1\lambda_1 \left[v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2}{\lambda_1}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n}{\lambda_1}v_n\right]=c_1\lambda_1x_1$$
where $x_1$ is a new vector and $x_1=v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2}{\lambda_1}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n}{\lambda_1}v_n$

This finishes the first iteration. And we can multiply $A$ to $x_1$ to start the 2nd iteration:
$$Ax_1=\lambda_1v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2^2}{\lambda_1}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n^2}{\lambda_1}v_n$$
Similarly, we can rearrange the above equation to:
$$Ax_1=\lambda_1 \left[v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2^2}{\lambda_1^2}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n^2}{\lambda_1^2}v_n\right]=\lambda_1x_2$$
where $x_2$ is a new vector and $x_2=v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2^2}{\lambda_1^2}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n^2}{\lambda_1^2}v_n$.
We can continue multiplying $A$ with the new vector we get from each iteration $k$ times:
$$Ax_{k-1}=\lambda_1 \left[v_1+\dfrac{c_2}{c_1}\dfrac{\lambda_2^k}{\lambda_1^k}v_2+\cdots+\dfrac{c_n}{c_1}\dfrac{\lambda_n^k}{\lambda_1^k}v_n\right]=\lambda_1x_k$$
Because $\lambda_1$ is the largest eigenvalue, therefore, the ratio $\dfrac{\lambda_i}{\lambda_1} < 1 \; \text{for all $i>1$}$. Thus when we increase $k$
 to sufficient large, the ratio of $\left(\dfrac{\lambda_i}{\lambda_1}\right)^{k}$ will be close to $0$ so that all the terms that contain this ratio can be neglected as $k$ grows:
 $$Ax_{k-1}=\lambda_1v_1$$
 Essentially, as $k$ is large enough, we will get the largest eigenvalue and its corresponding eigenvector. When implementing this power method, we usually normalize the resulting vector in each iteration. This can be done by factoring out the largest element in the vector, which will make the largest element in the vector equal to $1$. This normalization will get us the largest eigenvalue and its corresponding eigenvector at the same time. Let's take a look of the following example.

 You may ask when should we stop the iteration? The basic stopping criteria should be one of the three: in the consecutive iterations,  


*   the difference between eigenvalues is less than some specified tolerance;
*   the angle between eigenvectors is smaller than a threshold ;
*   or the norm of the residual vector is small enough.



We know from last section that the largest eigenvalue is $4$ for matrix $
\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}$,
now use the power method to find the largest eigenvalue and the associated eigenvector. You can use the initial vector $[1, 1]$ to start the iteration.



**1st iteration**:

$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
1     \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\5\\\end{bmatrix} =5\begin{bmatrix} 0.4\\1\\\end{bmatrix} $$
**2nd iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.4     \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\3.8\\ \end{bmatrix} =3.8\begin{bmatrix} 0.5263\\1\\ \end{bmatrix}  $$
**3rd iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.5263    \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\ 4.0526\\ \end{bmatrix} = 4.0526\begin{bmatrix} 0.4935\\1\\ \end{bmatrix}  $$
**4th iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.4935    \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\ 3.987\\ \end{bmatrix} = 3.987\begin{bmatrix} 0.5016\\1\\ \end{bmatrix}   $$
**5th iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.5016    \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\ 4.0032\\ \end{bmatrix} = 4.0032\begin{bmatrix} 0.4996\\1\\ \end{bmatrix}    $$
**6th iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.4996   \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\ 3.9992\\ \end{bmatrix} = 3.9992\begin{bmatrix} 0.5001\\1\\ \end{bmatrix}     $$
**7th iteration**:
$$\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}
\begin{bmatrix}
0.5001   \\
1    \\
\end{bmatrix}=\begin{bmatrix} 2\\ 4.0002\\ \end{bmatrix} = 4.0002\begin{bmatrix} 0.5000\\1\\ \end{bmatrix}     $$

We can see after $7$ iterations, the eigenvalue converged to 4 with $[0.5, 1]$as the corresponding eigenvector.

**Implement the power method in Python**

In [2]:
import numpy as np

In [3]:
def normalize(x):
  index_of_largest_component = np.argmax(np.abs(x))
  fac = x[index_of_largest_component]
  x_n = x/fac
  return fac, x_n

In [4]:
x = np.array([1, 1])
# Convert vector x to column form
# x=x[:,np.newaxis]
a = np.array([[0, 2],
              [2, 3]])

for i in range(8):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 3.999949137887188
Eigenvector: [0.50000636 1.        ]


In [5]:
x = np.array([1, 1])
# Convert vector x to column form
x=x[:,np.newaxis]
a = np.array([[0, 2],
              [2, 3]])

for i in range(8):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: [3.99994914]
Eigenvector: [[0.50000636]
 [1.        ]]


**The inverse power method**

The eigenvalues of the inverse matrix $A^{-1}$ are the reciprocals of the eigenvalues of $A$. We can take advantage of this feature as well as the power method to get the smallest eigenvalue of $A$, this will be basis of the inverse power method. The steps are very simple, instead of multiplying $A$ as described above, we just multiply $A^{-1}$ for our iteration to find the largest eigenvalue $\dfrac{1}{\lambda_1}$ of $A^{-1}$, where $\lambda_1$ will be the smallest value of the eigenvalues for $A$. As for the inverse of the matrix, in practice, we can use the methods we covered in the previous chapter to calculate it.

Find the smallest eigenvalue and eigenvector for $\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}$.

In [6]:
from numpy.linalg import inv

In [7]:
x = np.array([1,1])

a = np.array([[0, 2],
              [2, 3]])
a_inv = inv(a)

for i in range(8):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Smallest eigenvalue of A:', 1/lambda_1)
print('Its corresponding eigenvector:', x)

Smallest eigenvalue of A: -0.9998855617013162
Its corresponding eigenvector: [ 1.         -0.49994278]


**The shifted power method**

In some cases, we need to find all the eigenvalues and eigenvectors instead of the largest and smallest. One simple but inefficient way is to use the shifted power method (we will introduce you an efficient way in next section). Given $Ax=\lambda x$, and $\lambda_1$
 is the largest eigenvalue obtained by the power method, then we can have:
 $$[A-\lambda_1I]x=\alpha x$$
 where $\alpha$'s are the eigenvalues of the shifted matrix  $A-\lambda_1 I$, which will be $0, \lambda_2-\lambda_1, \lambda_3-\lambda_1,\dots, \lambda_n-\lambda_1$.

 Now if we apply the power method to the shifted matrix, then we can determine the largest eigenvalue of the shifted matrix, i.e. $\alpha_k$. Since $\alpha_k=\lambda_k-\lambda_1$, we can get the eigenvalue $\lambda_k$
 easily. We can repeat this process many times to find the all the other eigenvalues. But you can see that, it involves a lot of work! A better method for finding all the eigenvalues is to use the $QR$ method.

**The QR Method**

The $QR$ method is a preferred iterative method to find all the eigenvalues of a matrix (but not the eigenvectors at the same time). The idea is based on the following two concepts:

*   similar matrices will have the same eigenvalues and associated eigenvectors. Two square matrices $A$ and $B$
 are similar if:
 $$A=C^{-1}BC$$
 where $C$ is an invertible matrix.
*   The $QR$ method is a way to decompose a matrix into two matrices $Q$ and $R$
, where $Q$ is an orthogonal matrix, and $R$ is an upper triangular matrix. An orthogonal matrix has the features: $Q^{-1}=Q^{T}$ which means $Q^{-1}Q=Q^{T}Q=I$

**How do we link these two concepts to find the eigenvalues**?

Say we have a matrix $A_{0}$ whose eigenvalues must be determined. At the $k$-th step (starting with $k=0$) we can perform the QR decomposition and get $A_{k}=Q_{k}R_{k}$ where $Q_{k}$ is an orthogonal matrix and $R_k$ is an upper triangular matrix. We then form $A_{k+1}=R_{k}Q_{k}$ which we note that
$$A_{k+1}=Q_{k}^{-1}Q_{k}R_{k}Q_{k}=Q_{k}^{-1}A_{k}Q_{k}$$
therefore, all the $A_k$ are similar, as we discussed above they all have the same eigenvalues. As the iteration goes, we will eventually converge to an upper triangular matrix form:
$$A_k=R_kQ_k=\begin{bmatrix}
\lambda_{1}       &   X        & \dots     &   X      \\
0       &  \lambda_{2}        & \dots     &   X       \\
\vdots  &  \vdots   &   \vdots  &   \vdots  \\   
0       &   0        & \dots     &  \lambda_{n}         \\
\end{bmatrix}
$$
where the diagonal values are the eigenvalues of the matrix. In each iteration of the $QR$ method, factoring a matrix into an orthogonal and an upper triangular matrix can be done by using a special matrix called **Householder matrix**. We will not go into the mathematical details how you get the $Q$
and $R$ from the matrix, instead, we will use the Python function to obtain the two matrices directly.


 Use the $\verb|qr|$ function in numpy.linalg to decompose matrix $\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}$. And verify the results.

In [8]:
import numpy as np
from numpy.linalg import qr

In [9]:
a = np.array([[0, 2],
              [2, 3]])

q, r = qr(a)

print('Q:', q)
print('R:', r)

b = np.dot(q, r)
print('QR:', b)

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]]


Use the $QR$ method to get the eigenvalues of matrix $\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}$. Do $20$ iterations, and print out the $1$st, $5$th, $10$th, and $20$th iteration.

In [10]:
a = np.array([[0, 2],
              [2, 3]])
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Iteration 1:
[[3. 2.]
 [2. 0.]]
Iteration 5:
[[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]]
Iteration 10:
[[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]]
Iteration 20:
[[ 4.00000000e+00  9.09484250e-12]
 [ 9.09494702e-12 -1.00000000e+00]]


We can see after the $5$th iteration, the eigenvalues converge to the correct ones.

Now, we will take a look how to get the eigenvalues and eigenvectors in Python easily using the built-in function.

**Eigenvalues and Eigenvectors in Python**

Though the methods we introduced so far look complicated, the actually calculation of the eigenvalues and eigenvectors in Python is fairly easy. The main built-in function in Python to solve the eigenvalue/eigenvector problem for a square array is the $\verb|eig|$ function in numpy.linalg. Let's see how we can use it.

 Calculate the eigenvalues and eigenvectors for matrix $\begin{bmatrix}
0    &  2     \\
2       &   3   \\  
\end{bmatrix}$.

In [11]:
import numpy as np
from numpy.linalg import eig

In [12]:
a = np.array([[0, 2],
              [2, 3]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


Compute the eigenvalues and eigenvectors for matrix $\begin{bmatrix}
2    &  2 & 4     \\
1       &   3 & 5  \\  
2 & 3 & 4\\
\end{bmatrix}$.

In [13]:
a = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [ 8.80916362  0.92620912 -0.73537273]
E-vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
